FROM node:23-alpine3.20 as deps

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install


FROM node:23-alpine3.20 as build

WORKDIR /usr/src/app
COPY --from=deps /usr/src/app/node_modules /node_modules
COPY . .
RUN npm run build

RUN npm ci -f --only=production && npm cache clean --force

FROM node:23-alpine3.20 as prod
WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/prisma ./prisma
COPY --from=build /usr/src/app/dist ./dist

EXPOSE 3000

CMD ["node","dist/main.js"]